### ISSUE TITLE
Package 1.2 installs with dependency conflicts

### ISSUE THREAD

**Issue by thomasliebenau** [JKISoftware/JKI-State-Machine-Objects#37]
Hi,

package 1.2 installs with conflicts in dependencies:

![screen shot 2017-03-21 at 13 26 01](https://cloud.githubusercontent.com/assets/25008402/24147491/bdec48b8-0e3a-11e7-8e93-70fd223636be.png)

Many (all?)  lvclass files are duplicated to the package base folder and VIs are relinked to them except regestry-smo.lvclass which raises a dependency conflict.

![screen shot 2017-03-21 at 13 21 00](https://cloud.githubusercontent.com/assets/25008402/24147622/60a09d0c-0e3b-11e7-86cf-045bc9e34642.png)

With package 1.1.17 folder looked like that:
![screen shot 2017-03-21 at 13 27 53](https://cloud.githubusercontent.com/assets/25008402/24147669/9f3673a2-0e3b-11e7-89a5-e458c92dec8e.png)

with best regards,
Thomas Liebenau

**Comment by francois-normandin** [comment]
Thanks Thomas. I'll fix that this morning.

**Comment by francois-normandin** [comment]
Well, I think something is corrupted in the linker info of one of the classes, which causes VIPM to believe that the classes associated with the Facade class are in the wrong location. The duplicate does not make sense otherwise.  I thought I had a cross-link somewhere, or a circular dependency, but that's not it. It will take a bit more work to get that right.

In the meantime, I think the code still works after relinking as the classes are really duplicates, but people should wait for the next build before trying it out.

**Comment by francois-normandin** [comment]
So, the culprit is that one of my dependencies had been moved into the test folder, which was not supposed to get built into the package. By pulling this dependency into the package, the file was put at the root and it duplicated the classes it depended on... causing a linkage issue.
