### ISSUE TITLE
Launch Dependency method is partially functional with error input.

### ISSUE THREAD

**Issue by gcodetechnology** [JKISoftware/JKI-State-Machine-Objects#65]
LaunchDependency.vi functions with an error input, but not the same as with no error input.

When there is an error input, my expectation is either that the method does not function at all or, if it does, that it functions the same way it would without an error input.

![SMO - Add Dependency](https://user-images.githubusercontent.com/8042326/67641142-1b2dbb00-f8bd-11e9-8097-fb7df7e6d6c3.jpg)

**Comment by francois-normandin** [comment]
Hi Eric, 
I agree with that statement.

Note that this has been fixed in the 1.4 branch currently under review (see screenshot below), but you make me realize that it should go one step further and simply bypass all in the event of an upstream error. The diagram below is essentially a no-op, but still takes a non-zero amount of time to execute, which is suboptimal and easy to see why:
![image](https://user-images.githubusercontent.com/11728548/67675341-45cb5280-f955-11e9-9d08-e1b847f38bf2.png)

Thanks for catching this!
Francois

**Comment by francois-normandin** [comment]
This is now fixed in the 1.4.0 beta release branch.
https://github.com/JKISoftware/JKI-State-Machine-Objects/tree/release/1.4.0_beta
