### ISSUE TITLE
[Feature] Handle Error.vi Improvements

### ISSUE THREAD

**Issue by ciozi137** [JKISoftware/JKI-State-Machine-Objects#69]
- Issues
-- Issue 1:
If a state in process.vi throws an error the execution is directed to the _Error Handler_ state. _Error Handler_ calls the overrideable method **Handle Error.vi** to handle the error. However, at this time there is doesn't appear to be an elegant way to inject information about which state caused the error because **Handle Error.vi** does not have an input terminal.
-- Issue 2:
**Handle Error.vi** does not have an output to call states in response to any specific error

![image](https://user-images.githubusercontent.com/26659428/74863188-74fa3b00-531b-11ea-80b1-ccf9c412ebd1.png)

- Possible Solutions
1. User adds VIs to assist in parsing sources of the error and queuing additional states. (However does not follow OO design)

![image](https://user-images.githubusercontent.com/26659428/74864324-690f7880-531d-11ea-98b3-9fb47b5e7f0a.png)

2. Add input and output terminals to **Handle Error.vi** (Allows user to override method to handle their errors, but would break existing code)

![image](https://user-images.githubusercontent.com/26659428/74864339-6ca2ff80-531d-11ea-8c3e-0c9116420456.png)

**Comment by francois-normandin** [comment]
@ciozi137, this node is probably going to stay as it is for backward compatibility but your point brings an interesting discussion.

I'd hesitate to go the way you propose at the framework level because acting directly on a string introduces too many risks in terms of encapsulation. Allowing anyone to override acting on a queue (whether on string or any other queuing mechanism) introduces difficult to manage indeterminism in the resulting post-error actions. 
1- A child class might enqueue states that are incompatible with the states enqueued by the parent method
2- Acting on a queue inside a subVI seems a good idea, but years of practice with the JKI State Machine led many to officially call this practice the number 1 thing to avoid with the JKI SM (see @jimkring 's blog about this [here](https://blog.jki.net/products/state-machine/jki-state-machine-best-practices).

The "Handle Error" override is intended for developers to enqueue a message (private event) aimed at being picked up by the State Machine on the next iteration. This is why no more states are enqueued (except "Exit"). _That being said, I see that the other already enqueued states are not cleared, so that is in contradiction with what I'm actually saying here because the remaining states will be executed before catching the private event..._ 

So to wrap up my thoughts here, I think there is definitely a need to refactor the error handling case in the SMO. You bring a very valid use case where the developer wants to modify the state as soon as an error occurred, and currently there is a possibility that it will continue enqueuing undesired states. However, I would suggest you act in response to an error by either 1) running a post-error macro or 2) use a private event in your Handle error override. 

Here is what I would propose: 
![image](https://user-images.githubusercontent.com/11728548/74867226-47fd5680-5322-11ea-8f69-61f5f82dbcef.png)

**Comment by ciozi137** [comment]
Hi @francois-normandin,
Thanks for your detailed reply - there is a lot of good food for thought in there. I especially like your suggestion to clear the state queue in the "Error Handler" state. I suspect not clearing the state queue has been causing me many problems in terms of recovering from an error.

I would also like to point you to [discussions ](https://github.com/JKISoftware/JKI-State-Machine/pull/14) I've been having with @jimkring regarding the "Error Handler" state knowing which state threw the error.

**Comment by francois-normandin** [comment]
This template will be available as a DropVI from the palette of SMO 1.4.0.
Editor integration will have to be done through modification of templates in the separate template packages.

Ref here: https://github.com/JKISoftware/JKI-SMO-Templates/issues/4
