### ISSUE TITLE
FindDependency(byKey) reports dependency found even if SMO has no dependencies.

### ISSUE THREAD

**Issue by gcodetechnology** [JKISoftware/JKI-State-Machine-Objects#75]
**Description**
SMO dependency is reported to be found even when none exist.

**To Reproduce**
Use FindDependency(byKey).vi on any SMO subsystem that has no dependencies.

**Expected behavior**
The "Found?" output of the function should return False.

<img width="820" alt="FindDependency(byKey)" src="https://user-images.githubusercontent.com/8042326/126878712-d0703c6a-f1b8-40cb-9b96-8c3abd845760.png">

**Comment by francois-normandin** [comment]
Totally right. And I can't even blame the OR'ing of an empty array for this. There's actually another bug on that screenshot: an empty string in the key input coupled with an invalid (just destroyed) dependency, might result in found=true. Not very likely, I know, but still possible.

Solution should therefore filter for both empty array of dependencies and for empty key input.

Thanks Eric!

**Comment by francois-normandin** [comment]
Here are the proposed fixes that will be available in the 1.4.0 branch until released.

![image](https://user-images.githubusercontent.com/11728548/126898742-0ce5d678-9c20-47a5-98e9-543d1dd13900.png)

* Filter for empty array of dependencies and empty key
* Now uses "positive" logic instead of "not equal + Not"
* Now checks if dependency is a valid SMO.

**Comment by francois-normandin** [comment]
Done. In feature/stable140 branch until released
